# main menu navigation
menu:
  Home: /
  About: /about
  Archive: /archives

widgets:
  - tag
  - archive
  - recent_posts
  - category
  - profile

# social config
social:
  zhihu:
  twitter: 
  facebook: 
  linkedin: chark1es
  instagram: 
  github: chark1es

user:
  name: Charles
  avatar:
  location: UC San Diego
  description: Computer Science Major
  footnotes: # footnotes

# documents: https://github.com/utterance/utterances
# API config: https://utteranc.es/
comment_utteranc:
  enable: false
  repo: chark1es/charkes.org # your blog repo


# documents: https://valine.js.org/quickstart.html
comment_valine:
  enable: false
  appId:
  appKey:

comment_disqus:
    enable: false
    url:  # the url of your website main domain like this https://xxx.xxx/
    name: # the short name in disqus

# dark
# light
# user-can-set
appearance: dark # Default value is auto

# Miscellaneous
favicon: images/favicon.ico

friend_links:
  - title: Ngoc Nguyen
    link: https://www.linkedin.com/in/ngoclnguyen/
  - title: Jason Tran
    link: https://enscribe.dev


# Google Analytics
ga_track_id:
ga_domain:

# Baidu Analytics
ba_track_id:

# picture of about page
about_pic: about.png

image_zoom:
  enable: true